//===----------------------------------------------------------------------===//
//
// Part of the Zanna project, under the GNU GPL v3.
// See LICENSE for license information.
//
//===----------------------------------------------------------------------===//
//
// File: il/runtime/RuntimeNameMap.hpp
// Purpose: Central mapping from canonical Zanna.* runtime symbols to C rt_* symbols.
// Key invariants: Every canonical entry maps to exactly one C symbol; lookups
//                 return std::nullopt when no mapping exists.
// Ownership/Lifetime: Header-only static data; no runtime allocations.
// Links: RuntimeNameMap.inc
//
//===----------------------------------------------------------------------===//

/// @file
/// @brief Declares canonical-to-C runtime symbol alias lookup.

#pragma once

#include <optional>
#include <string_view>

namespace il::runtime {

/// @brief Maps a canonical Zanna.* runtime symbol to its C rt_* implementation.
/// @details Each entry pairs a high-level Zanna namespace symbol (e.g.,
///          "Zanna.String.Substring") with the corresponding low-level C
///          runtime function name (e.g., "rt_str_substr"). The native code
///          generator uses this mapping to resolve IL extern references to
///          linkable C symbols.
struct RuntimeNameAlias {
    std::string_view canonical; ///< High-level Zanna.* symbol name (e.g., "Zanna.String.get_Length").
    std::string_view runtime;   ///< Low-level C runtime symbol (e.g., "rt_str_len").
};

/// @brief Static map of Zanna.* names to rt_* symbols used by native backends.
inline const RuntimeNameAlias kRuntimeNameAliases[] = {
#define RUNTIME_NAME_ALIAS(canon, impl) RuntimeNameAlias{canon, impl},
// Generated by rtgen from runtime.def
#include "il/runtime/RuntimeNameMap.inc"
#undef RUNTIME_NAME_ALIAS
};

/// @brief Resolve a canonical Zanna.* runtime name to the C runtime symbol.
/// @param name Fully qualified canonical runtime symbol.
/// @return Mapped symbol when present; std::nullopt otherwise.
inline std::optional<std::string_view> mapCanonicalRuntimeName(std::string_view name) {
    for (const auto &alias : kRuntimeNameAliases) {
        if (alias.canonical == name)
            return alias.runtime;
    }
    return std::nullopt;
}

} // namespace il::runtime
