REM An object reference compares with NOTHING through =, <>, and IS.
CLASS Box
  PUBLIC size AS INTEGER
END CLASS

FUNCTION Maybe(make AS BOOLEAN) AS Box
  IF make THEN RETURN NEW Box()
  RETURN NOTHING
END FUNCTION

DIM b AS Box
IF b = NOTHING THEN PRINT "unset = NOTHING"
IF b IS NOTHING THEN PRINT "unset IS NOTHING"
IF NOT (b <> NOTHING) THEN PRINT "unset not <> NOTHING"

b = NEW Box()
IF b <> NOTHING THEN PRINT "set <> NOTHING"
IF NOTHING <> b THEN PRINT "NOTHING <> set"
IF NOT (b IS NOTHING) THEN PRINT "set not IS NOTHING"

DIM o AS OBJECT
o = b
IF o <> NOTHING THEN PRINT "object <> NOTHING"

IF Maybe(TRUE) <> NOTHING THEN PRINT "made"
IF Maybe(FALSE) = NOTHING THEN PRINT "not made"
IF Maybe(FALSE) IS NOTHING THEN PRINT "not made IS NOTHING"

b = NOTHING
PRINT b = NOTHING
END
