//===----------------------------------------------------------------------===//
//
// Part of the Zanna project, under the GNU GPL v3.
// See LICENSE for license information.
//
//===----------------------------------------------------------------------===//
//
// File: src/tools/d3d11_shader_bake/d3d11_shader_bake.c
// Purpose: Build-time generator that compiles the D3D11 backend's embedded HLSL with the
//          runtime's exact D3DCompile flags and writes the DXBC as a C include, so Windows
//          processes create their shaders without spending seconds in the HLSL compiler.
// Key invariants:
//   - Every manifest entry must compile; any failure exits nonzero and writes no output.
//   - The output records the manifest digest it was generated from and is replaced atomically.
// Ownership/Lifetime:
//   - Compiler blobs live until the output is written; the process exit releases the rest.
// Links: src/runtime/graphics/3d/backend/vgfx3d_backend_d3d11_shader_manifest.inc,
//        src/runtime/CMakeLists.txt
//
//===----------------------------------------------------------------------===//

/// @file
/// @brief Bakes the D3D11 backend shader manifest to an embedded-DXBC C include.
/// @details Usage: `zanna_d3d11_shader_bake <output.inc>`. Entries compile concurrently (the
///   D3D compiler is thread-safe); the include defines one `vgfx3d_d3d11_dxbc_<member>` array per
///   manifest entry plus `VGFX3D_D3D11_EMBEDDED_BYTECODE_DIGEST`.

#define COBJMACROS
#define WIN32_LEAN_AND_MEAN
#include <d3d11.h>
#include <d3dcompiler.h>
#include <windows.h>

#include "vgfx3d_backend.h"
#include "vgfx3d_backend_d3d11_shared.h"

#include <stdarg.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <wchar.h>

#define VGFX3D_STR_IMPL(x) #x
#define VGFX3D_STR(x) VGFX3D_STR_IMPL(x)
#include "vgfx3d_backend_d3d11_shaders.inc"
/* The manifest expands the shader-source accessors defined above. */
#include "vgfx3d_backend_d3d11_shader_manifest.inc"

/// @brief One manifest entry and its compiler result.
typedef struct {
    const char *member;
    const char *source;
    const char *entry;
    const char *target;
    ID3DBlob *bytecode;
    ID3DBlob *diagnostics;
    HRESULT hr;
} bake_job_t;

/// @brief Compile one manifest entry; runs on its own thread.
/// @param[in,out] parameter The `bake_job_t` to compile.
/// @return Always zero; the outcome is recorded in the job.
static DWORD WINAPI bake_compile(LPVOID parameter) {
    bake_job_t *job = (bake_job_t *)parameter;
    if (!job->source) {
        job->hr = E_OUTOFMEMORY;
        return 0;
    }
    job->hr = D3DCompile(job->source,
                         strlen(job->source),
                         "vgfx3d_d3d11",
                         NULL,
                         NULL,
                         job->entry,
                         job->target,
                         VGFX3D_D3D11_SHADER_COMPILE_FLAGS,
                         0,
                         &job->bytecode,
                         &job->diagnostics);
    return 0;
}

/// @brief Append formatted text to the output file, recording any write failure.
/// @param[in] out Open output stream.
/// @param[in,out] ok Cleared when a write fails.
/// @param[in] format printf-style format string.
static void bake_printf(FILE *out, int *ok, const char *format, ...) {
    va_list args;
    va_start(args, format);
    if (vfprintf(out, format, args) < 0)
        *ok = 0;
    va_end(args);
}

/// @brief Write the embedded-DXBC include for every compiled job.
/// @param[in] out Open output stream.
/// @param[in] jobs Compiled manifest entries in manifest order.
/// @param[in] count Number of entries in @p jobs.
/// @return Nonzero when every byte was written.
static int bake_write_include(FILE *out, const bake_job_t *jobs, size_t count) {
    int ok = 1;
    bake_printf(out,
                &ok,
                "//===---------------------------------------------------------------------"
                "-===//\n"
                "// Generated by zanna_d3d11_shader_bake from "
                "vgfx3d_backend_d3d11_shaders.inc. Do not edit.\n"
                "// DXBC for every VGFX3D_D3D11_SHADER_LIST entry, compiled with "
                "VGFX3D_D3D11_SHADER_COMPILE_FLAGS.\n"
                "//===---------------------------------------------------------------------"
                "-===//\n\n"
                "#define VGFX3D_D3D11_EMBEDDED_BYTECODE_DIGEST UINT64_C(0x%016llx)\n",
                (unsigned long long)vgfx3d_d3d11_shader_manifest_digest());
    for (size_t i = 0; i < count && ok; i++) {
        const unsigned char *bytes =
            (const unsigned char *)ID3D10Blob_GetBufferPointer(jobs[i].bytecode);
        SIZE_T size = ID3D10Blob_GetBufferSize(jobs[i].bytecode);
        bake_printf(
            out,
            &ok,
            "\n/* %s (%s), %llu bytes */\nstatic const unsigned char vgfx3d_d3d11_dxbc_%s[] = {",
            jobs[i].entry,
            jobs[i].target,
            (unsigned long long)size,
            jobs[i].member);
        for (SIZE_T b = 0; b < size && ok; b++)
            bake_printf(out, &ok, "%s0x%02x,", (b % 16u) == 0 ? "\n    " : " ", bytes[b]);
        bake_printf(out, &ok, "\n};\n");
    }
    return ok;
}

/// @brief Compile the manifest and atomically publish the include named by `argv[1]`.
/// @param[in] argc Argument count; exactly one output path is required.
/// @param[in] argv UTF-16 arguments, so non-ASCII build directories survive.
/// @return 0 on success, 1 on a compile or I/O failure, 2 on usage errors.
int wmain(int argc, wchar_t **argv) {
#define BAKE_JOB(member, source, entry, target)                                                    \
    {#member, source, entry, target, NULL, NULL, E_FAIL},
    bake_job_t jobs[] = {VGFX3D_D3D11_SHADER_LIST(BAKE_JOB)};
#undef BAKE_JOB
    const size_t count = sizeof(jobs) / sizeof(jobs[0]);
    HANDLE threads[sizeof(jobs) / sizeof(jobs[0])];
    wchar_t *staging;
    size_t staging_chars;
    FILE *out;
    int failed = 0;

    if (argc != 2 || !argv[1][0]) {
        fprintf(stderr, "usage: zanna_d3d11_shader_bake <output.inc>\n");
        return 2;
    }
    staging_chars = wcslen(argv[1]) + sizeof(".tmp");
    staging = (wchar_t *)malloc(staging_chars * sizeof(wchar_t));
    if (!staging || swprintf(staging, staging_chars, L"%ls.tmp", argv[1]) < 0) {
        fprintf(stderr, "zanna_d3d11_shader_bake: cannot form the staging path\n");
        return 1;
    }

    for (size_t i = 0; i < count; i++) {
        threads[i] = CreateThread(NULL, 0, bake_compile, &jobs[i], 0, NULL);
        if (!threads[i])
            bake_compile(&jobs[i]);
    }
    for (size_t i = 0; i < count; i++) {
        if (threads[i]) {
            WaitForSingleObject(threads[i], INFINITE);
            CloseHandle(threads[i]);
        }
    }
    for (size_t i = 0; i < count; i++) {
        if (SUCCEEDED(jobs[i].hr) && jobs[i].bytecode)
            continue;
        failed = 1;
        fprintf(stderr,
                "zanna_d3d11_shader_bake: %s (%s) failed to compile (hr=0x%08lx)\n",
                jobs[i].entry,
                jobs[i].target,
                (unsigned long)jobs[i].hr);
        if (jobs[i].diagnostics) {
            fprintf(stderr,
                    "%.*s\n",
                    (int)ID3D10Blob_GetBufferSize(jobs[i].diagnostics),
                    (const char *)ID3D10Blob_GetBufferPointer(jobs[i].diagnostics));
        }
    }
    if (failed)
        return 1;

    if (_wfopen_s(&out, staging, L"wb") != 0 || !out) {
        fprintf(stderr, "zanna_d3d11_shader_bake: cannot create %ls\n", staging);
        return 1;
    }
    if (!bake_write_include(out, jobs, count)) {
        fclose(out);
        _wremove(staging);
        fprintf(stderr, "zanna_d3d11_shader_bake: failed writing %ls\n", staging);
        return 1;
    }
    if (fclose(out) != 0 ||
        !MoveFileExW(staging, argv[1], MOVEFILE_REPLACE_EXISTING | MOVEFILE_WRITE_THROUGH)) {
        _wremove(staging);
        fprintf(stderr, "zanna_d3d11_shader_bake: cannot publish %ls\n", argv[1]);
        return 1;
    }
    return 0;
}
