#!/usr/bin/env python3
# Script: generate_tzdata_subset.py
# Purpose: Regenerate the embedded deterministic timezone subset used by
#          src/runtime/localization/rt_timezone.c.

from __future__ import annotations

import argparse
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "src/runtime/localization/rt_tzdata_generated.inc"


NEW_YORK = [
    (1741503600, -14400, 1, "EDT", "2025-03-09T07:00:00Z"),
    (1762063200, -18000, 0, "EST", "2025-11-02T06:00:00Z"),
    (1772953200, -14400, 1, "EDT", "2026-03-08T07:00:00Z"),
    (1793512800, -18000, 0, "EST", "2026-11-01T06:00:00Z"),
]

SYDNEY = [
    (1743868800, 36000, 0, "AEST", "2025-04-05T16:00:00Z"),
    (1759593600, 39600, 1, "AEDT", "2025-10-04T16:00:00Z"),
    (1775318400, 36000, 0, "AEST", "2026-04-04T16:00:00Z"),
    (1791043200, 39600, 1, "AEDT", "2026-10-03T16:00:00Z"),
]


NEW_YORK_DOC = """\
/// @brief Inclusive 2025\u20132026 UTC rule transitions for America/New_York.
/// @details The owning zone's EST base rule covers earlier instants; the final
///          EST entry remains effective for later instants in this subset."""

SYDNEY_DOC = """\
/// @brief Inclusive 2025\u20132026 UTC rule transitions for Australia/Sydney.
/// @details The owning zone's AEDT base rule covers earlier instants; the final
///          AEDT entry remains effective for later instants in this subset."""

ZONES_DOC = """\
/// @brief Canonical lookup table for every zone embedded in this data subset.
/// @details Fixed-offset records have no transition array. Returned TimeZone
///          handles borrow addresses from this process-lifetime table."""


def transition_array(name: str, rows: list[tuple[int, int, int, str, str]], doc: str) -> str:
    """Render one documented transition table.

    The Doxygen comment is emitted from here so the generated include stays
    both self-documenting and byte-for-byte reproducible from this script.
    """
    lines = [doc.rstrip("\n"), f"static const rt_tz_transition_t {name}[] = {{"]
    for ts, offset, is_dst, abbr, iso in rows:
        lines.append(f'    {{{ts}LL, {offset}, {is_dst}, "{abbr}"}}, // {iso}')
    lines.append("};")
    return "\n".join(lines)


def render() -> str:
    return f"""//===----------------------------------------------------------------------===//
//
// Part of the Zanna project, under the GNU GPL v3.
// See LICENSE for license information.
//
//===----------------------------------------------------------------------===//
//
// File: src/runtime/localization/rt_tzdata_generated.inc
// Purpose: Generated embedded IANA time-zone subset consumed by rt_timezone.c.
// Key invariants:
//   - Transition arrays are sorted by UTC effective timestamp.
//   - Offsets are seconds east of UTC.
//   - The subset is host-independent and intentionally covers only curated
//     zones required by the runtime determinism tests.
//   - A zone's base rule applies before its first transition; its final
//     transition remains active after the generated time window.
// Ownership/Lifetime: Static data only.
// Links: scripts/generate_tzdata_subset.py, docs/internals/generated-files.md
//
//===----------------------------------------------------------------------===//

/**
 * @file
 * @brief Defines the generated, host-independent embedded time-zone subset.
 * @details Supplies sorted inclusive transition tables and process-lifetime
 * zone records consumed directly by @ref rt_timezone.c; regenerate this file
 * from the named script when the curated data version changes.
 */

// Generated by scripts/generate_tzdata_subset.py.
// Data subset version: zanna-tz-subset-2026a.

{transition_array("g_tz_transitions_new_york", NEW_YORK, NEW_YORK_DOC)}

{transition_array("g_tz_transitions_sydney", SYDNEY, SYDNEY_DOC)}

{ZONES_DOC}
static rt_tz_zone_t g_tz_zones[] = {{
    {{"UTC", 0, 0, "UTC", NULL, 0}},
    {{"Etc/UTC", 0, 0, "UTC", NULL, 0}},
    {{"Asia/Tokyo", 32400, 0, "JST", NULL, 0}},
    {{"America/New_York", -18000, 0, "EST", g_tz_transitions_new_york,
     sizeof(g_tz_transitions_new_york) / sizeof(g_tz_transitions_new_york[0])}},
    {{"Australia/Sydney", 39600, 1, "AEDT", g_tz_transitions_sydney,
     sizeof(g_tz_transitions_sydney) / sizeof(g_tz_transitions_sydney[0])}},
}};
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="verify the checked-in file")
    args = parser.parse_args()

    text = render()
    if args.check:
        current = OUT.read_text(encoding="utf-8")
        if current != text:
            raise SystemExit(f"{OUT} is stale; run scripts/generate_tzdata_subset.py")
        print(f"{OUT} is current")
        return 0
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
