//===----------------------------------------------------------------------===//
//
// Part of the Zanna project, under the GNU GPL v3.
// See LICENSE for license information.
//
//===----------------------------------------------------------------------===//
//
// File: src/tools/common/packaging/IconGenerator.hpp
// Purpose: Generate platform-specific icon formats from a source PNG image.
//          - macOS: ICNS container with embedded PNGs at multiple sizes.
//          - Windows: ICO container with embedded PNGs at multiple sizes.
//          - Linux: Individual PNG files at standard sizes.
//
// Key invariants:
//   - Source images are square RGBA buffers at least 32 pixels per side; standard
//     icon sizes are generated by resizing up or down as needed.
//   - ICNS uses big-endian fields; embeds PNG data directly (modern format).
//   - ICO uses little-endian fields and embeds PNG data for every generated size.
//   - Output is returned as byte vectors — no file I/O in the generator.
//
// Ownership/Lifetime:
//   - All output returned as std::vector<uint8_t> (caller-owned).
//
// Links: PkgPNG.hpp (resize + encode), MacOSPackageBuilder.hpp,
//        LinuxPackageBuilder.hpp
//
//===----------------------------------------------------------------------===//

/// @file
/// @brief Declares dependency-free platform icon generation from RGBA images.
/// @details A validated square source image is resized and PNG-encoded into
///          macOS ICNS, Windows ICO, or Linux hicolor payloads. All generated
///          images and container bytes are returned in caller-owned storage.

#pragma once

#include "PkgPNG.hpp"

#include <cstdint>
#include <map>
#include <vector>

namespace zanna::pkg {

/// @brief Generate macOS ICNS icon data from a source image.
///
/// @details Produces the modern standard ICNS type records from 32 through 1024
///          pixels. Each record embeds a resized PNG after its four-byte type
///          and big-endian size; the global header carries `"icns"` and the
///          complete big-endian container size.
/// @param srcImage Source RGBA image.
/// @return ICNS file data.
/// @throws PNGError When the source image or a 32-bit format size is invalid.
std::vector<uint8_t> generateIcns(const PkgImage &srcImage);

/// @brief Generate Windows ICO icon data from a source image.
///
/// @details Produces PNG-backed records at 16, 24, 32, 48, 64, 128, and 256
///          pixels. The output consists of the six-byte ICONDIR, one 16-byte
///          directory entry per image, and the PNG blocks in matching order.
/// @param srcImage Source RGBA image.
/// @return ICO file data.
/// @throws PNGError When the source image or a 32-bit format size is invalid.
std::vector<uint8_t> generateIco(const PkgImage &srcImage);

/// @brief Generate Zanna's built-in fallback toolchain icon as an RGBA image.
///
/// @details The packagers use this when an installer is packaging Zanna itself
///          rather than an end-user project with a manifest-provided icon. The
///          image is generated procedurally for Windows resources, Linux
///          hicolor icons, and macOS ICNS resources.
/// @return A 256x256 RGBA image suitable for generateIcns/generateIco and
///         generateMultiSizePngs.
PkgImage defaultZannaToolchainIconImage();

/// @brief Generate multi-size PNG icons from a source image.
///
/// @details Generates standard Linux hicolor sizes 16, 32, 48, 128, and 256,
///          using the pixel dimension as the ordered map key.
/// @param srcImage Source RGBA image.
/// @return Map of pixel size to PNG file data.
/// @throws PNGError When source validation, resizing, or encoding fails.
std::map<uint32_t, std::vector<uint8_t>> generateMultiSizePngs(const PkgImage &srcImage);

} // namespace zanna::pkg
