//===----------------------------------------------------------------------===//
//
// Part of the Zanna project, under the GNU GPL v3.
// See LICENSE for license information.
//
//===----------------------------------------------------------------------===//
//
// File: src/tools/common/packaging/LinuxRuntimeStubGen.cpp
// Purpose: Generate the Zanna self-extracting Linux bundle runtime stub.
//
// Key invariants:
//   - The shell runtime is POSIX sh and requires only standard base system tools.
//   - Payload bytes are never interpreted by the shell; they are streamed to tar.
//   - The extracted entry point is executed with the caller's argv.
//
// Ownership/Lifetime:
//   - Pure byte generation and structural verification helpers.
//
// Links: LinuxRuntimeStubGen.hpp
//
//===----------------------------------------------------------------------===//

/// @file
/// @brief Implements generation and structural verification of Linux self-extracting bundles.
/// @details The generated POSIX shell prefix safely extracts, caches, verifies,
///          and launches an appended gzip-compressed tar payload without FUSE.

#include "LinuxRuntimeStubGen.hpp"
#include "PkgHash.hpp"
#include "PkgUtils.hpp"
#include "PkgVerify.hpp"

#include <algorithm>
#include <sstream>
#include <string_view>

namespace zanna::pkg {
namespace {

/// @brief Quote a value as one POSIX shell word.
/// @param value Arbitrary text to quote.
/// @return Single-quoted literal with embedded quotes escaped.
std::string shellSingleQuote(std::string_view value) {
    std::string out;
    out.reserve(value.size() + 2);
    out.push_back('\'');
    for (char c : value) {
        if (c == '\'')
            out += "'\\''";
        else
            out.push_back(c);
    }
    out.push_back('\'');
    return out;
}

/// @brief Validate a normalized package-relative token embedded in the shell stub.
/// @param value Token to validate.
/// @param fieldName Human-readable field name used in diagnostics.
/// @throws std::runtime_error If the token is multiline, unsafe, or non-normalized.
void validateStubToken(const std::string &value, const char *fieldName) {
    validateSingleLineField(value, fieldName);
    const std::string clean = sanitizePackageRelativePath(value, fieldName);
    if (clean != value)
        throw std::runtime_error(std::string(fieldName) + " was not normalized: " + value);
}

/// @brief Validate an optional payload SHA-256 digest embedded in the stub.
/// @details Empty strings are accepted for standalone stub tests. Complete
///          Bundles generated by buildLinuxAppImage() always provide a
///          lowercase 64-character digest of the appended gzip payload.
/// @param value Digest text to validate.
/// @throws std::runtime_error when @p value is non-empty and not SHA-256 hex.
void validateOptionalSha256(const std::string &value) {
    if (value.empty())
        return;
    if (value.size() != 64)
        throw std::runtime_error("Linux bundle payload SHA-256 must be 64 hex characters");
    for (char c : value) {
        const bool digit = c >= '0' && c <= '9';
        const bool lower = c >= 'a' && c <= 'f';
        if (!digit && !lower)
            throw std::runtime_error("Linux bundle payload SHA-256 must be lowercase hexadecimal");
    }
}

/// @brief Locate the marker terminating the textual runtime stub.
/// @param data Complete candidate bundle bytes.
/// @return Iterator to the marker's first byte, or `data.end()` when absent.
std::vector<uint8_t>::const_iterator payloadMarkerIt(const std::vector<uint8_t> &data) {
    const std::string marker = std::string(kLinuxRuntimePayloadMarker) + "\n";
    return std::search(data.begin(),
                       data.end(),
                       reinterpret_cast<const uint8_t *>(marker.data()),
                       reinterpret_cast<const uint8_t *>(marker.data()) + marker.size());
}

/// @brief Extract a single shell assignment value from the generated stub.
/// @details The runtime stub writes simple single-quoted assignments before
///          the payload marker. This helper is intentionally narrow and is used
///          only by verifyLinuxAppImage() to read payload_sha256.
/// @param text Stub text before the binary payload.
/// @param name Assignment name including no trailing equals sign.
/// @return The unquoted assignment value, or an empty string when absent.
std::string shellAssignmentValue(std::string_view text, std::string_view name) {
    const std::string needle = std::string(name) + "='";
    const size_t start = text.find(needle);
    if (start == std::string_view::npos)
        return {};
    size_t pos = start + needle.size();
    std::string out;
    while (pos < text.size()) {
        char c = text[pos++];
        if (c == '\'') {
            if (pos + 2 < text.size() && text[pos] == '\\' && text[pos + 1] == '\'' &&
                text[pos + 2] == '\'') {
                out.push_back('\'');
                pos += 3;
                continue;
            }
            return out;
        }
        out.push_back(c);
    }
    return {};
}

} // namespace

/// @brief Generate the executable POSIX shell prefix for a Linux bundle.
/// @details Validates and shell-quotes all embedded values, emits cache and
///          extraction hardening, optional SHA-256 verification, command-line
///          interfaces, and the final payload marker.
/// @param params Cache identity, payload entry path, digest, and interface options.
/// @return UTF-8 shell stub bytes ending immediately after the payload marker line.
/// @throws std::runtime_error If an embedded token or digest is invalid.
std::vector<uint8_t> buildLinuxRuntimeStub(const LinuxRuntimeStubParams &params) {
    validateStubToken(params.cacheName, "Linux bundle cache name");
    validateStubToken(params.entryPath, "Linux bundle entry path");
    validateOptionalSha256(params.payloadSha256);

    std::ostringstream script;
    script << "#!/bin/sh\n"
              "set -eu\n"
              "umask 077\n"
              "self=$0\n"
              "cache_name="
           << shellSingleQuote(params.cacheName)
           << "\n"
              "entry_path="
           << shellSingleQuote(params.entryPath)
           << "\n"
              "payload_sha256="
           << shellSingleQuote(params.payloadSha256)
           << "\n"
              "case \"$entry_path\" in /*|..|../*|*/../*|*/..) echo \"Unsafe Linux bundle entry "
              "path: $entry_path\" >&2; exit 2 ;; esac\n"
              "say() {\n"
              "    case \"${ZANNA_BUNDLE_QUIET:-}\" in 1|true|TRUE|yes|YES) return ;; esac\n"
              "    if [ -t 2 ] && [ -z \"${NO_COLOR:-}\" ]; then\n"
              "        printf '\\033[1;34mZanna bundle\\033[0m  %s\\n' \"$*\" >&2\n"
              "    else\n"
              "        printf 'Zanna bundle: %s\\n' \"$*\" >&2\n"
              "    fi\n"
              "}\n"
              "fail() { printf 'Zanna bundle error: %s\\n' \"$*\" >&2; exit 2; }\n"
              "check_no_symlink_components() {\n"
              "    checked_path=$1\n"
              "    case \"$checked_path\" in /*) current=/; rest=${checked_path#/} ;; *) "
              "fail \"cache path must be absolute: $checked_path\" ;; esac\n"
              "    while [ -n \"$rest\" ]; do\n"
              "        component=${rest%%/*}\n"
              "        if [ \"$component\" = \"$rest\" ]; then rest=; else rest=${rest#*/}; fi\n"
              "        [ -n \"$component\" ] || continue\n"
              "        if [ \"$current\" = / ]; then current=/$component; else "
              "current=$current/$component; fi\n"
              "        [ ! -L \"$current\" ] || fail \"refusing symlinked cache path component: "
              "$current\"\n"
              "    done\n"
              "}\n"
              "sha256_file() {\n"
              "    if command -v sha256sum >/dev/null 2>&1; then sha256sum \"$1\" | awk '{print "
              "$1}';\n"
              "    elif command -v shasum >/dev/null 2>&1; then shasum -a 256 \"$1\" | awk "
              "'{print $1}';\n"
              "    elif command -v openssl >/dev/null 2>&1; then openssl dgst -sha256 -r \"$1\" "
              "| awk '{print $1}';\n"
              "    else fail \"no SHA-256 tool is available (tried sha256sum, shasum, and "
              "openssl)\"; fi\n"
              "}\n"
              "verify_payload() {\n"
              "    [ -n \"$payload_sha256\" ] || return 0\n"
              "    actual_sha256=$(sha256_file \"$1\")\n"
              "    [ \"$actual_sha256\" = \"$payload_sha256\" ] || fail \"payload checksum "
              "mismatch\"\n"
              "}\n"
              "if [ -n \"${XDG_CACHE_HOME:-}\" ]; then\n"
              "    cache_root=$XDG_CACHE_HOME\n"
              "elif [ -n \"${HOME:-}\" ]; then\n"
              "    cache_root=$HOME/.cache\n"
              "else\n"
              "    cache_root=${TMPDIR:-/tmp}\n"
              "fi\n"
              "cache_root=${cache_root%/}/zanna\n"
              "case \"$cache_root\" in /*) ;; *) fail \"cache root must be absolute: "
              "$cache_root\" ;; esac\n"
              "cache_key=$cache_name\n"
              "if [ -n \"$payload_sha256\" ]; then cache_key=$cache_name-$payload_sha256; fi\n"
              "extract_dir=$cache_root/$cache_key\n"
              "stamp_file=$extract_dir/.payload.sha256\n"
              "payload_line=$(awk '/^"
           << kLinuxRuntimePayloadMarker
           << "$/ { print NR + 1; exit }' \"$self\")\n"
              "[ -n \"$payload_line\" ] || fail \"payload marker not found\"\n"
              "case \"${1:-}\" in\n";
    script << "    --zanna-bundle-help";
    if (params.appImageInterface)
        script << "|--appimage-help";
    script << ")\n"
              "        echo \"Zanna self-extracting Linux bundle options:\"\n"
              "        echo \"  --zanna-bundle-extract  safely extract to ./zanna-bundle-root\"\n"
              "        echo \"  --zanna-bundle-cache    print this bundle's cache directory\"\n"
              "        echo \"  --zanna-bundle-help     show this help\"\n";
    if (params.appImageInterface)
        script << "        echo \"  --appimage-help/extract AppImage-compatible aliases\"\n";
    script << "        exit 0 ;;\n"
              "    --zanna-bundle-cache) printf '%s\\n' \"$extract_dir\"; exit 0 ;;\n"
              "    --zanna-bundle-extract";
    if (params.appImageInterface)
        script << "|--appimage-extract";
    script << ")\n"
              "        extract_target=./zanna-bundle-root\n"
              "        [ ! -e \"$extract_target\" ] && [ ! -L \"$extract_target\" ] || fail "
              "\"$extract_target already exists; move or remove it first\"\n"
              "        tmp_dir=$(mktemp -d \"./.zanna-bundle-extract.XXXXXX\")\n"
              "        trap 'rm -rf \"${tmp_dir:-}\"' EXIT HUP INT TERM\n"
              "        payload_file=$tmp_dir/payload.tar.gz\n"
              "        tail -n +$payload_line \"$self\" > \"$payload_file\"\n"
              "        say \"verifying payload\"\n"
              "        verify_payload \"$payload_file\"\n"
              "        mkdir \"$tmp_dir/root\"\n"
              "        tar xzf \"$payload_file\" -C \"$tmp_dir/root\"\n"
              "        rm -f \"$payload_file\"\n"
              "        mv \"$tmp_dir/root\" \"$extract_target\"\n"
              "        tmp_dir=\n"
              "        trap - EXIT HUP INT TERM\n"
              "        printf 'Extracted Zanna bundle to %s\\n' \"$extract_target\"\n"
              "        exit 0 ;;\n"
              "esac\n"
              "check_no_symlink_components \"$cache_root\"\n"
              "mkdir -p \"$cache_root\"\n"
              "check_no_symlink_components \"$cache_root\"\n"
              "[ -d \"$cache_root\" ] && [ ! -L \"$cache_root\" ] || fail \"cache root is not a "
              "real directory: $cache_root\"\n"
              "chmod 700 \"$cache_root\" || fail \"cannot secure cache root: $cache_root\"\n"
              "if command -v stat >/dev/null 2>&1; then\n"
              "    cache_uid=$(stat -c %u \"$cache_root\" 2>/dev/null || printf '')\n"
              "    current_uid=$(id -u)\n"
              "    [ -z \"$cache_uid\" ] || [ \"$cache_uid\" = \"$current_uid\" ] || fail "
              "\"cache root is owned by uid $cache_uid, not $current_uid\"\n"
              "fi\n"
              "[ ! -L \"$extract_dir\" ] || fail \"refusing symlinked cache directory: "
              "$extract_dir\"\n"
              "refresh=0\n";
    if (params.appImageInterface)
        script << "refresh_request=${ZANNA_BUNDLE_REFRESH:-${ZANNA_APPIMAGE_CLEAN_CACHE:-}}\n";
    else
        script << "refresh_request=${ZANNA_BUNDLE_REFRESH:-}\n";
    script << "case \"$refresh_request\" in "
              "1|true|TRUE|yes|YES) refresh=1 ;; esac\n"
              "cache_is_valid() {\n"
              "    [ \"$refresh\" = 0 ] || return 1\n"
              "    [ -d \"$extract_dir\" ] && [ ! -L \"$extract_dir\" ] || return 1\n"
              "    [ -x \"$extract_dir/$entry_path\" ] && [ ! -L \"$extract_dir/$entry_path\" ] "
              "|| return 1\n"
              "    if [ -n \"$payload_sha256\" ]; then\n"
              "        [ -f \"$stamp_file\" ] && [ ! -L \"$stamp_file\" ] || return 1\n"
              "        [ \"$(cat \"$stamp_file\")\" = \"$payload_sha256\" ] || return 1\n"
              "    fi\n"
              "    return 0\n"
              "}\n"
              "if ! cache_is_valid; then\n"
              "    lock_dir=$cache_root/.$cache_key.lock\n"
              "    lock_owned=\n"
              "    attempts=0\n"
              "    while ! mkdir \"$lock_dir\" 2>/dev/null; do\n"
              "        [ ! -L \"$lock_dir\" ] || fail \"refusing symlinked extraction lock: "
              "$lock_dir\"\n"
              "        lock_pid=$(cat \"$lock_dir/pid\" 2>/dev/null || printf '')\n"
              "        case \"$lock_pid\" in ''|*[!0-9]*) lock_pid= ;; esac\n"
              "        if [ -z \"$lock_pid\" ] && [ \"$attempts\" -eq 0 ]; then\n"
              "            attempts=1\n"
              "            sleep 1\n"
              "            continue\n"
              "        fi\n"
              "        if [ -z \"$lock_pid\" ] || ! kill -0 \"$lock_pid\" 2>/dev/null; then\n"
              "            rm -rf \"$lock_dir\"\n"
              "            attempts=0\n"
              "            continue\n"
              "        fi\n"
              "        attempts=$((attempts + 1))\n"
              "        [ \"$attempts\" -lt 30 ] || fail \"timed out waiting for another extraction "
              "process\"\n"
              "        sleep 1\n"
              "    done\n"
              "    lock_owned=$lock_dir\n"
              "    printf '%s\\n' \"$$\" > \"$lock_dir/pid\"\n"
              "    trap 'rm -rf \"${tmp_dir:-}\" \"${lock_owned:-}\"' EXIT HUP INT TERM\n"
              "    if ! cache_is_valid; then\n"
              "        say \"preparing verified payload\"\n"
              "        tmp_dir=$(mktemp -d \"${cache_root%/}/.$cache_name.tmp.XXXXXX\")\n"
              "        payload_file=$tmp_dir/payload.tar.gz\n"
              "        tail -n +$payload_line \"$self\" > \"$payload_file\"\n"
              "        verify_payload \"$payload_file\"\n"
              "        mkdir \"$tmp_dir/root\"\n"
              "        tar xzf \"$payload_file\" -C \"$tmp_dir/root\"\n"
              "        rm -f \"$payload_file\"\n"
              "        [ -f \"$tmp_dir/root/$entry_path\" ] && [ ! -L "
              "\"$tmp_dir/root/$entry_path\" ] || fail \"payload entry is missing or unsafe: "
              "$entry_path\"\n"
              "        chmod +x \"$tmp_dir/root/$entry_path\"\n"
              "        if [ -n \"$payload_sha256\" ]; then printf '%s' \"$payload_sha256\" > "
              "\"$tmp_dir/root/.payload.sha256\"; fi\n"
              "        old_dir=$cache_root/.$cache_key.old.$$\n"
              "        rm -rf \"$old_dir\"\n"
              "        if [ -e \"$extract_dir\" ]; then mv \"$extract_dir\" \"$old_dir\"; fi\n"
              "        mv \"$tmp_dir/root\" \"$extract_dir\"\n"
              "        tmp_dir=\n"
              "        rm -rf \"$old_dir\"\n"
              "    fi\n"
              "    rm -rf \"$lock_owned\"\n"
              "    lock_owned=\n"
              "    trap - EXIT HUP INT TERM\n"
              "fi\n"
              "say \"launching $entry_path\"\n"
              "exec \"$extract_dir/$entry_path\" \"$@\"\n"
           << kLinuxRuntimePayloadMarker << "\n";
    const std::string text = script.str();
    return std::vector<uint8_t>(text.begin(), text.end());
}

/// @brief Combine a generated runtime stub with a verified gzip-tar payload.
/// @param params Runtime options; the payload digest is recomputed and overrides
///        `params.payloadSha256` in the generated copy.
/// @param payloadTarGz Complete gzip-compressed tar payload.
/// @return Self-extracting bundle bytes containing the stub followed by the payload.
/// @throws std::runtime_error If the payload is not valid gzip-compressed tar data
///         or the runtime parameters are invalid.
std::vector<uint8_t> buildLinuxAppImage(const LinuxRuntimeStubParams &params,
                                        const std::vector<uint8_t> &payloadTarGz) {
    if (payloadTarGz.size() < 2 || payloadTarGz[0] != 0x1F || payloadTarGz[1] != 0x8B)
        throw std::runtime_error("Linux bundle payload must be a gzip-compressed tar archive");
    std::ostringstream payloadError;
    if (!verifyTarGz(payloadTarGz, payloadError)) {
        throw std::runtime_error("Linux bundle payload is not a valid tar.gz archive:\n" +
                                 payloadError.str());
    }
    LinuxRuntimeStubParams checkedParams = params;
    checkedParams.payloadSha256 = sha256Hex(payloadTarGz.data(), payloadTarGz.size());
    std::vector<uint8_t> out = buildLinuxRuntimeStub(checkedParams);
    out.insert(out.end(), payloadTarGz.begin(), payloadTarGz.end());
    return out;
}

/// @brief Verify the framing, digest, and compressed-tar payload of a Linux bundle.
/// @param data Complete candidate self-extracting bundle.
/// @param err Optional destination for a diagnostic describing the first failure.
/// @return `true` when the shebang, marker, optional checksum, and tarball are valid.
bool verifyLinuxAppImage(const std::vector<uint8_t> &data, std::string *err) {
    if (data.size() < 4 || data[0] != '#' || data[1] != '!') {
        if (err)
            *err = "Linux bundle: missing executable runtime stub\n";
        return false;
    }
    const auto marker = payloadMarkerIt(data);
    if (marker == data.end()) {
        if (err)
            *err = "Linux bundle: missing payload marker\n";
        return false;
    }
    const std::string markerText = std::string(kLinuxRuntimePayloadMarker) + "\n";
    const auto payload = marker + static_cast<std::ptrdiff_t>(markerText.size());
    const std::string_view stubText(reinterpret_cast<const char *>(data.data()),
                                    static_cast<size_t>(marker - data.begin()));
    const std::string expectedSha = shellAssignmentValue(stubText, "payload_sha256");
    if (!expectedSha.empty()) {
        try {
            validateOptionalSha256(expectedSha);
            const size_t payloadOffset = static_cast<size_t>(payload - data.begin());
            const size_t payloadLen = static_cast<size_t>(data.end() - payload);
            const std::string actualSha = sha256Hex(data.data() + payloadOffset, payloadLen);
            if (actualSha != expectedSha) {
                if (err)
                    *err = "Linux bundle: payload SHA-256 mismatch\n";
                return false;
            }
        } catch (const std::exception &ex) {
            if (err)
                *err = std::string("Linux bundle: invalid payload SHA-256 metadata: ") + ex.what() +
                       "\n";
            return false;
        }
    }
    if (payload == data.end() || static_cast<size_t>(data.end() - payload) < 2u ||
        payload[0] != 0x1F || payload[1] != 0x8B) {
        if (err)
            *err = "Linux bundle: appended payload is not gzip data\n";
        return false;
    }
    const std::vector<uint8_t> payloadBytes(payload, data.end());
    std::ostringstream payloadError;
    if (!verifyTarGz(payloadBytes, payloadError)) {
        if (err)
            *err = "Linux bundle: invalid tar.gz payload: " + payloadError.str();
        return false;
    }
    return true;
}

} // namespace zanna::pkg
