## Accept UPDATE_GOLDEN from -D or the environment.
include(${CMAKE_CURRENT_LIST_DIR}/GoldenUpdateMode.cmake)

if (NOT DEFINED ILC)
    message(FATAL_ERROR "ILC not set")
endif ()
if (NOT DEFINED IL_FILE)
    message(FATAL_ERROR "IL_FILE not set")
endif ()
if (NOT DEFINED EXPECT)
    message(FATAL_ERROR "EXPECT not set")
endif ()
# RUN_CMD selects the CLI form under test: the legacy top-level "-run" flag
# (default) or the "run" subcommand, which also accepts .il targets.
if (NOT DEFINED RUN_CMD)
    set(RUN_CMD "-run")
endif ()
execute_process(COMMAND ${ILC} ${RUN_CMD} ${IL_FILE} RESULT_VARIABLE res OUTPUT_VARIABLE out ERROR_VARIABLE err)
# Normalize Windows line endings
string(REPLACE "\r\n" "\n" out "${out}")
string(REPLACE "\r" "\n" out "${out}")
string(REPLACE "\r\n" "\n" err "${err}")
string(REPLACE "\r" "\n" err "${err}")
if (NOT res EQUAL 0)
    message(FATAL_ERROR "expected zero exit: ${res}\n${err}")
endif ()
string(STRIP "${out}" out)
if (NOT out STREQUAL "${EXPECT}")
    if (DEFINED UPDATE_GOLDEN AND DEFINED GOLDEN_FILE)
        file(WRITE ${GOLDEN_FILE} "${out}\n")
        message(STATUS "Updated golden: ${GOLDEN_FILE}")
    else ()
        message(FATAL_ERROR "output mismatch: expected '${EXPECT}' got '${out}'")
    endif ()
endif ()
