//===----------------------------------------------------------------------===//
//
// Part of the Zanna project, under the GNU GPL v3.
// See LICENSE in the project root for license information.
//
//===----------------------------------------------------------------------===//
//
// File: src/runtime/io/rt_file_path.c
// Purpose: Translates BASIC runtime file mode descriptors into platform-specific
//          strings and open(2) flag combinations. Also exposes borrow helpers
//          for validated path text and arbitrary byte views into runtime-managed
//          ZannaString handles without copying the underlying data.
//
// Key invariants:
//   - Mode conversion routines return NULL or false on invalid input; no partial
//     results are produced.
//   - Borrowed string views are valid only for the lifetime of the ZannaString
//     handle they were derived from; callers must not cache the raw pointer.
//   - O_CLOEXEC is defined to 0 on platforms that lack it, ensuring safe use.
//   - Every RT_F_* mode enumerator maps to exactly one fopen mode string.
//
// Ownership/Lifetime:
//   - Borrowed string views do not transfer ownership; callers retain the
//     reference count on the originating ZannaString objects.
//   - Callers must release ZannaString handles through the standard ref-count
//     API; the borrow helpers here do not affect reference counts.
//
// Links: src/runtime/io/rt_file_path.h (public API),
//        src/runtime/io/rt_file.h (RtFile type and RT_F_* mode enum)
//
//===----------------------------------------------------------------------===//

#include "rt_file_path.h"
#include "rt_file.h"

#include "rt_heap.h"
#include "rt_internal.h"

#include <fcntl.h>
#include <string.h>

#ifdef _WIN32
#include <stdlib.h>
#include <windows.h>
#endif

#ifndef O_CLOEXEC
#define O_CLOEXEC 0
#endif

/// @brief Map a BASIC runtime file mode enumeration to a C stdio mode string.
/// @details Converts the runtime specific @ref RT_F_* enumerators to the
///          canonical mode strings understood by `fopen`.  Unsupported modes
///          yield `NULL` so the caller can signal an invalid combination.
/// @param mode BASIC runtime mode flag from the `RT_F_*` enumeration.
/// @return A null-terminated C string describing the desired mode, or `NULL`
///         when the mode is invalid.
const char *rt_file_mode_string(int32_t mode) {
    switch (mode) {
        case RT_F_INPUT:
            return "r";
        case RT_F_OUTPUT:
            return "w";
        case RT_F_APPEND:
            return "a";
        case RT_F_BINARY:
            return "rb+";
        case RT_F_RANDOM:
            return "rb+";
        default:
            return NULL;
    }
}

/// @brief Convert a textual file mode description into platform `open` flags.
/// @details Parses the `fopen`-style mode string generated by
///          @ref rt_file_mode_string (or provided by user code) and produces the
///          appropriate combination of flags for the low-level `open` call.  The
///          helper accepts `+`, `b`, and `t` modifiers, applies BASIC-mode creation
///          and Windows binary-I/O rules, and records the result in @p flags_out.
/// @param mode Null-terminated mode string to parse.
/// @param basic_mode BASIC OPEN mode enumerator used to refine creation and binary flags, or
///                   `RT_F_UNSPECIFIED` when no BASIC mode applies.
/// @param flags_out Output pointer that receives the computed flag bitmask. It
///                  must be non-null; it is reset to zero before validation.
/// @return `true` when the mode string is valid and the flags were written;
///         otherwise `false`.
int8_t rt_file_mode_to_flags(const char *mode, int32_t basic_mode, int *flags_out) {
    if (flags_out)
        *flags_out = 0;
    if (!mode || !mode[0] || !flags_out)
        return 0;

    int flags = 0;
    switch (mode[0]) {
        case 'r':
            flags = O_RDONLY;
            break;
        case 'w':
            flags = O_WRONLY | O_CREAT | O_TRUNC;
            break;
        case 'a':
            flags = O_WRONLY | O_CREAT | O_APPEND;
            break;
        default:
            return 0;
    }

    int plus = 0;
    int binary = 0;
    for (const char *p = mode + 1; *p; ++p) {
        if (*p == '+')
            plus = 1;
        else if (*p == 'b')
            binary = 1;
        else if (*p == 't')
            continue;
        else
            return 0;
    }

    if (plus) {
        flags &= ~(O_RDONLY | O_WRONLY);
        flags |= O_RDWR;
    }
    if (basic_mode == RT_F_BINARY || basic_mode == RT_F_RANDOM)
        flags |= O_CREAT;
#if defined(_WIN32)
    const int basic_text_mode =
        basic_mode == RT_F_INPUT || basic_mode == RT_F_OUTPUT || basic_mode == RT_F_APPEND;
    if (binary || basic_text_mode) {
#if defined(O_BINARY)
        flags |= O_BINARY;
#elif defined(_O_BINARY)
        flags |= _O_BINARY;
#endif
    }
#else
    (void)binary;
#endif
    flags |= O_CLOEXEC;

    *flags_out = flags;
    return 1;
}

/// @brief Obtain a borrowed C string view from a @ref ZannaString path value.
/// @details Validates the @p path handle and, when successful, updates
///          @p out_path to point at the underlying UTF-8 character buffer.
///          Ownership is not transferred; callers must ensure the
///          @ref ZannaString remains alive for the duration of the borrow.
/// @param path Runtime string handle describing a filesystem path.
/// @param out_path Optional output pointer updated to the borrowed C string.
/// @return `true` when the path handle is valid, otherwise `false`.
int8_t rt_file_path_from_vstr(const ZannaString *path, const char **out_path) {
    if (out_path)
        *out_path = NULL;
    if (!path || !rt_string_is_handle(path) || !path->data)
        return 0;
    size_t len = path->literal_len;
    if (path->heap && path->heap != RT_SSO_SENTINEL)
        len = rt_heap_len(path->data);
    if (memchr(path->data, '\0', len) != NULL)
        return 0;
    if (out_path)
        *out_path = path->data;
    return 1;
}

/// @brief Provide a byte-oriented view over a @ref ZannaString buffer.
/// @details Extracts a pointer to the underlying string data and reports its
///          length without copying.  Heap-backed strings derive their length via
///          @ref rt_heap_len, while literal strings return the stored
///          @ref ZannaString::literal_len value.  Callers must not mutate the
///          returned data.
/// @param s Runtime string handle to view.
/// @param data_out Optional output pointer updated to the raw byte buffer.
/// @return The number of bytes referenced by the string, or zero when the
///         handle is invalid.
size_t rt_file_string_view(const ZannaString *s, const uint8_t **data_out) {
    if (data_out)
        *data_out = NULL;
    if (!s || !rt_string_is_handle(s) || !s->data)
        return 0;
    if (data_out)
        *data_out = (const uint8_t *)s->data;
    if (s->heap && s->heap != RT_SSO_SENTINEL)
        return rt_heap_len(s->data);
    return s->literal_len;
}

/// @brief Obtain a borrowed byte view from a required runtime string.
/// @details Unlike rt_file_string_view(), an invalid handle invokes rt_trap() using @p context
///          (or a generic fallback) instead of returning a normal failure sentinel. The returned
///          pointer remains owned by @p s and is valid only while that string storage is alive.
/// @param s Runtime string handle that must be valid and backed by data.
/// @param[out] data_out Optional destination for the borrowed byte pointer; cleared before
///                      validation.
/// @param context Trap diagnostic to use for an invalid handle; may be NULL.
/// @return Number of bytes in the string view.
size_t rt_file_string_require_view(const ZannaString *s,
                                   const uint8_t **data_out,
                                   const char *context) {
    if (data_out)
        *data_out = NULL;
    if (!s || !rt_string_is_handle(s) || !s->data)
        rt_trap(context ? context : "invalid string");
    return rt_file_string_view(s, data_out);
}

#ifdef _WIN32
/// @brief Convert a UTF-8 C string to a freshly allocated wide-char string.
///
/// Used ubiquitously before calling the `W` variants of Win32/CRT
/// APIs — the `A` variants use the system ANSI codepage, which loses
/// data for non-ASCII filenames. Conversion is strict: malformed UTF-8
/// is rejected so file operations never target a replacement-character
/// path that differs from the caller's byte string. Caller owns the
/// returned buffer via `free`.
/// @param utf8 Null-terminated UTF-8 path to convert.
/// @return Newly allocated null-terminated wide path, or NULL for null input, invalid UTF-8,
///         conversion failure, or allocation failure.
wchar_t *rt_file_path_utf8_to_wide(const char *utf8) {
    if (!utf8)
        return NULL;

    int needed = MultiByteToWideChar(CP_UTF8, MB_ERR_INVALID_CHARS, utf8, -1, NULL, 0);
    if (needed <= 0)
        return NULL;

    wchar_t *wide = (wchar_t *)malloc((size_t)needed * sizeof(wchar_t));
    if (!wide)
        return NULL;

    if (MultiByteToWideChar(CP_UTF8, MB_ERR_INVALID_CHARS, utf8, -1, wide, needed) <= 0) {
        free(wide);
        return NULL;
    }
    return wide;
}

/// @brief Convert a wide-char string to a Zanna `rt_string` (UTF-8 encoded).
///
/// Two-pass conversion: first call with NULL output buffer to size
/// the target, then allocate and fill. Returns `rt_str_empty()` on
/// any failure so the caller can proceed without null-checking —
/// callers that need to distinguish "empty input" from "conversion
/// failure" should validate upstream.
/// @param wide Null-terminated Windows wide path to convert.
/// @return Runtime UTF-8 string on success; otherwise the shared empty runtime string.
rt_string rt_file_path_wide_to_string(const wchar_t *wide) {
    if (!wide)
        return rt_str_empty();

    int needed = WideCharToMultiByte(CP_UTF8, WC_ERR_INVALID_CHARS, wide, -1, NULL, 0, NULL, NULL);
    if (needed <= 0)
        return rt_str_empty();

    char *utf8 = (char *)malloc((size_t)needed);
    if (!utf8)
        return rt_str_empty();

    if (WideCharToMultiByte(CP_UTF8, WC_ERR_INVALID_CHARS, wide, -1, utf8, needed, NULL, NULL) <=
        0) {
        free(utf8);
        return rt_str_empty();
    }

    rt_string s = rt_string_from_bytes(utf8, strlen(utf8));
    free(utf8);
    return s ? s : rt_str_empty();
}
#endif
