//===----------------------------------------------------------------------===//
/// @file
/// @brief Implements reference-counted runtime arrays of double values.
/// @details Payload handles use the shared heap header layout and element-kind
///          validation. Checked access traps through the common array panic
///          path, compiler-proven fast access omits checks, and generated resize
///          logic applies copy-on-write before mutating shared storage.
///
//
// Part of the Zanna project, under the GNU GPL v3.
// See LICENSE for license information.
//
//===----------------------------------------------------------------------===//
//
// File: src/runtime/arrays/rt_array_f64.c
// Purpose: Implements dynamic array helpers for 64-bit floating-point (double)
//          arrays, mirroring rt_array_i64.c but using double elements. Provides
//          allocation, bounds-checked access, mutation, and resize logic through
//          the shared runtime heap.
//
// Key invariants:
//   - Array payloads are preceded by a rt_heap_hdr_t header in the heap layout.
//   - Out-of-bounds accesses delegate to rt_arr_oob_panic which aborts.
//   - Resize grows capacity to the requested logical length.
//   - IEEE 754 double precision semantics are preserved for all stored values.
//   - All indices are zero-based; length and capacity are stored in the header.
//
// Ownership/Lifetime:
//   - Arrays are reference-counted via the heap allocator.
//   - Callers must not cache raw double* pointers across calls that may resize.
//
// Links: src/runtime/arrays/rt_array_f64.h (public API),
//        src/runtime/arrays/rt_array.h (int32 variant, provides oob_panic),
//        src/runtime/arrays/rt_array_i64.h (int64 variant)
//
//===----------------------------------------------------------------------===//

#include "rt_array_f64.h"
#include "rt_array.h" // for rt_arr_oob_panic
#include "rt_internal.h"
#include "rt_platform.h"

#include <assert.h>
#include <limits.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/// @brief Return the heap header associated with a double array payload.
/// @details The payload pointer refers to element 0; the header precedes it in
///          memory and encodes length, capacity, and element kind.
/// @param payload Array payload pointer or NULL.
/// @return Heap header pointer, or NULL if @p payload is NULL.
rt_heap_hdr_t *rt_arr_f64_hdr(const double *payload) {
    return payload ? rt_heap_hdr((void *)(uintptr_t)payload) : NULL;
}

/// @brief Validate that a heap header describes an f64 runtime array.
/// @param hdr Header to validate.
/// @note Generated by the shared runtime-array helper macro.
RT_ARR_DEFINE_ASSERT_HEADER_FN(rt_arr_f64_assert_header, RT_ELEM_F64)
/// @brief Compute payload bytes required for an f64 capacity.
/// @param cap Number of element slots.
/// @return Required byte count, or zero according to overflow policy.
/// @note Generated by the shared runtime-array helper macro.
RT_ARR_DEFINE_PAYLOAD_BYTES_FN(rt_arr_f64_payload_bytes, double)

/// @brief Validate array bounds and panic on out-of-range access.
/// @details Traps via @ref rt_arr_oob_panic when @p arr is NULL or @p idx is
///          beyond the current logical length.
/// @param arr Array payload pointer.
/// @param idx Element index to validate.
static void rt_arr_f64_validate_bounds(double *arr, size_t idx) {
    if (!arr)
        rt_arr_oob_panic(idx, 0);

    rt_heap_hdr_t *hdr = rt_arr_f64_hdr(arr);
    rt_arr_f64_assert_header(hdr);

    size_t len = hdr->len;
    if (idx >= len)
        rt_arr_oob_panic(idx, len);
}

/// @brief Allocate a new array of doubles with length @p len.
/// @details Allocates a runtime heap array with matching length and capacity.
/// @param len Number of elements to allocate.
/// @return Payload pointer or NULL on allocation failure.
double *rt_arr_f64_new(size_t len) {
    return (double *)rt_heap_alloc(RT_HEAP_ARRAY, RT_ELEM_F64, sizeof(double), len, len);
}

/// @brief Increment the reference count on the array payload.
/// @details No-op when @p arr is NULL.
/// @param arr Array payload pointer.
void rt_arr_f64_retain(double *arr) {
    if (!arr)
        return;
    rt_heap_hdr_t *hdr = rt_arr_f64_hdr(arr);
    rt_arr_f64_assert_header(hdr);
    rt_heap_retain(arr);
}

/// @brief Decrement the reference count and free on zero.
/// @details No-op when @p arr is NULL.
/// @param arr Array payload pointer.
void rt_arr_f64_release(double *arr) {
    if (!arr)
        return;
    rt_heap_hdr_t *hdr = rt_arr_f64_hdr(arr);
    rt_arr_f64_assert_header(hdr);
    rt_heap_release(arr);
}

/// @brief Return the logical length of the array.
/// @details Returns 0 for NULL arrays for convenience.
/// @param arr Array payload pointer (may be NULL).
/// @return Number of elements in the array.
size_t rt_arr_f64_len(double *arr) {
    if (!arr)
        return 0;
    rt_heap_hdr_t *hdr = rt_arr_f64_hdr(arr);
    rt_arr_f64_assert_header(hdr);
    return hdr->len;
}

/// @brief Return the current capacity of the array.
/// @details Returns 0 for NULL arrays.
/// @param arr Array payload pointer (may be NULL).
/// @return Capacity in elements.
size_t rt_arr_f64_cap(double *arr) {
    if (!arr)
        return 0;
    rt_heap_hdr_t *hdr = rt_arr_f64_hdr(arr);
    rt_arr_f64_assert_header(hdr);
    return hdr->cap;
}

/// @brief Read an element with bounds checking.
/// @details Traps on NULL arrays or out-of-range indices.
/// @param arr Array payload pointer.
/// @param idx Element index to read.
/// @return The element value at @p idx.
double rt_arr_f64_get(double *arr, size_t idx) {
    rt_arr_f64_validate_bounds(arr, idx);
    return arr[idx];
}

/// @brief Write an element with bounds checking.
/// @details Traps on NULL arrays or out-of-range indices.
/// @param arr Array payload pointer.
/// @param idx Element index to write.
/// @param value Value to store.
void rt_arr_f64_set(double *arr, size_t idx, double value) {
    rt_arr_f64_validate_bounds(arr, idx);
    arr[idx] = value;
}

/// @brief Read a double element after the compiler has proved the access safe.
/// @param arr Non-null array payload.
/// @param idx Compiler-proven in-bounds index.
/// @return Value stored at @p idx.
double rt_arr_f64_get_fast(double *arr, size_t idx) {
    return arr[idx];
}

/// @brief Write a double element after the compiler has proved the access safe.
/// @param arr Non-null array payload.
/// @param idx Compiler-proven in-bounds index.
/// @param value Value to store.
void rt_arr_f64_set_fast(double *arr, size_t idx, double value) {
    arr[idx] = value;
}

/// @brief Copy a sequence of elements between payload buffers.
/// @details Traps when either pointer is NULL and @p count is non-zero.
/// @param dst Destination payload pointer.
/// @param src Source payload pointer.
/// @param count Number of elements to copy.
void rt_arr_f64_copy_payload(double *dst, const double *src, size_t count) {
    if (count == 0)
        return;

    if (!dst || !src)
        rt_arr_oob_panic(0, count);

    if (count > SIZE_MAX / sizeof(double))
        rt_arr_oob_panic(0, count);
    memcpy(dst, src, count * sizeof(double));
}

/// @brief Reallocate unique f64 array storage to a requested length.
/// @param[in,out] hdr_inout Header pointer updated after reallocation.
/// @param[in,out] payload_inout Payload pointer updated after reallocation.
/// @param new_len Requested logical length.
/// @return Zero on success or `-1` on size/allocation/header failure.
/// @note Generated by the shared runtime-array helper macro.
RT_ARR_DEFINE_GROW_IN_PLACE_FN(rt_arr_f64_grow_in_place, double, rt_arr_f64_payload_bytes)
/// @brief Resize an f64 array under copy-on-write ownership rules.
/// @param[in,out] a_inout Address of the payload handle; a null payload
///                allocates a fresh array.
/// @param new_len Requested logical length.
/// @return Zero on success or `-1` on invalid input or allocation failure.
/// @note Generated by the shared runtime-array helper macro.
RT_ARR_DEFINE_RESIZE_FN(rt_arr_f64_resize,
                        double,
                        rt_arr_f64_hdr,
                        rt_arr_f64_assert_header,
                        rt_arr_f64_new,
                        rt_arr_f64_copy_payload,
                        rt_arr_f64_release,
                        rt_arr_f64_grow_in_place)
