//===----------------------------------------------------------------------===//
/// @file
/// @brief Implements reference-counted runtime arrays of 32-bit integers.
/// @details Array handles point at contiguous payload elements whose shared heap
///          header stores logical length, capacity, element kind, and reference
///          count. Checked access traps on invalid indices, optimized entry
///          points rely on compiler-proven bounds, and macro-generated resize
///          helpers either grow unique storage in place or return a copied
///          allocation according to shared runtime array policy.
///
//
// Part of the Zanna project, under the GNU GPL v3.
// See LICENSE for license information.
//
//===----------------------------------------------------------------------===//
//
// File: src/runtime/arrays/rt_array.c
// Purpose: Implements the dynamic generic array helpers (int32_t elements) that
//          back BASIC's DIM statement and collection operations. Provides
//          reference-counted storage, bounds checking, copy-on-write semantics,
//          and resize logic through the shared runtime heap.
//
// Key invariants:
//   - Array payloads are preceded in memory by a rt_heap_hdr_t header.
//   - Out-of-bounds accesses call rt_arr_oob_panic which prints a diagnostic
//     and aborts; no partial reads or writes are performed.
//   - Copy-on-write: mutating a shared array triggers a full copy before write.
//   - Resize doubles capacity to amortise allocation cost.
//   - VM and native runtimes share this module to avoid behavioural divergence.
//   - All indices are zero-based int32_t values.
//
// Ownership/Lifetime:
//   - Arrays are reference-counted via the heap allocator.
//   - Callers must retain/release arrays through the heap API; raw pointers are
//     not safe to cache across any call that may trigger a resize.
//
// Links: src/runtime/arrays/rt_array.h (public API),
//        src/runtime/arrays/rt_array_i64.h (int64 variant),
//        src/runtime/arrays/rt_array_str.h (string variant)
//
//===----------------------------------------------------------------------===//

#include "rt_array.h"
#include "rt_internal.h"
#include "rt_platform.h"

#include <assert.h>
#include <limits.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/// @brief Retrieve the heap header for a runtime array payload.
/// @details Delegates to @ref rt_heap_hdr while tolerating null payloads so
///          callers can interrogate optional handles without branching.
/// @param payload Array payload pointer (may be `NULL`).
/// @return Header describing the allocation, or `NULL` when @p payload is null.
rt_heap_hdr_t *rt_arr_i32_hdr(const int32_t *payload) {
    return payload ? rt_heap_hdr((void *)(uintptr_t)payload) : NULL;
}

/// @brief Trap execution due to an out-of-bounds access.
/// @details Formats a descriptive message and delegates to @ref rt_trap so the
///          VM error-handling stack can intercept the condition when available.
/// @param idx Index that triggered the violation.
/// @param len Array length used for diagnostics.
void rt_arr_oob_panic(size_t idx, size_t len) {
    char buf[128];
    snprintf(buf, sizeof(buf), "rt_arr_i32: index %zu out of bounds (len=%zu)", idx, len);
    rt_trap(buf);
    abort();
}

/// @brief Validate that a heap header describes an i32 runtime array.
/// @param hdr Header to validate.
/// @note Generated by the shared runtime-array helper macro.
RT_ARR_DEFINE_ASSERT_HEADER_FN(rt_arr_i32_assert_header, RT_ELEM_I32)
/// @brief Compute payload bytes required for an i32 element count.
/// @param cap Number of element slots.
/// @return Required byte count according to shared overflow policy.
/// @note Generated by the shared runtime-array helper macro.
RT_ARR_DEFINE_PAYLOAD_BYTES_FN(rt_arr_i32_payload_bytes, int32_t)

/// @brief Verify that an index falls inside the logical length of an array.
/// @details Checks the array pointer, confirms the backing header is valid, and
///          compares @p idx against the recorded length.  Violations delegate to
///          @ref rt_arr_oob_panic which aborts the program.
/// @param arr Runtime array payload.
/// @param idx Zero-based index being accessed.
static void rt_arr_i32_validate_bounds(int32_t *arr, size_t idx) {
    if (!arr)
        rt_arr_oob_panic(idx, 0);

    rt_heap_hdr_t *hdr = rt_arr_i32_hdr(arr);
    rt_arr_i32_assert_header(hdr);

    size_t len = hdr->len;
    if (idx >= len)
        rt_arr_oob_panic(idx, len);
}

/// @brief Allocate a new array with @p len elements.
/// @details Requests storage from the shared heap allocator and returns the
///          payload pointer.  The allocation is zero-initialised and tracks both
///          logical length and capacity via the heap header.
/// @param len Requested element count; the capacity matches this value.
/// @return Pointer to the array payload, or `NULL` when allocation fails.
int32_t *rt_arr_i32_new(size_t len) {
    return (int32_t *)rt_heap_alloc(RT_HEAP_ARRAY, RT_ELEM_I32, sizeof(int32_t), len, len);
}

/// @brief Increase the reference count for an array payload.
/// @details Guards against null pointers and validates the heap metadata before
///          delegating to @ref rt_heap_retain.
/// @param arr Array payload pointer.
void rt_arr_i32_retain(int32_t *arr) {
    if (!arr)
        return;
    rt_heap_hdr_t *hdr = rt_arr_i32_hdr(arr);
    rt_arr_i32_assert_header(hdr);
    rt_heap_retain(arr);
}

/// @brief Decrease the reference count for an array payload.
/// @details Validates the associated heap header prior to delegating to
///          @ref rt_heap_release so copy-on-write invariants remain intact.
/// @param arr Array payload pointer.
void rt_arr_i32_release(int32_t *arr) {
    if (!arr)
        return;
    rt_heap_hdr_t *hdr = rt_arr_i32_hdr(arr);
    rt_arr_i32_assert_header(hdr);
    rt_heap_release(arr);
}

/// @brief Retrieve the logical element count for the array.
/// @details Returns zero for null arrays so callers can handle optional
///          references without extra branching.
/// @param arr Array payload pointer.
/// @return Number of elements currently in use.
size_t rt_arr_i32_len(int32_t *arr) {
    if (!arr)
        return 0;
    rt_heap_hdr_t *hdr = rt_arr_i32_hdr(arr);
    rt_arr_i32_assert_header(hdr);
    return hdr->len;
}

/// @brief Retrieve the reserved capacity for the array.
/// @details A null optional handle reports zero; non-null input is validated as
///          an i32 array before the header capacity is read.
/// @param arr Array payload pointer.
/// @return Number of elements that fit without reallocating.
size_t rt_arr_i32_cap(int32_t *arr) {
    if (!arr)
        return 0;
    rt_heap_hdr_t *hdr = rt_arr_i32_hdr(arr);
    rt_arr_i32_assert_header(hdr);
    return hdr->cap;
}

/// @brief Read an element after checking bounds.
/// @param arr Array payload pointer.
/// @param idx Zero-based index to access.
/// @return Value stored at the requested index.
int32_t rt_arr_i32_get(int32_t *arr, size_t idx) {
    rt_arr_i32_validate_bounds(arr, idx);
    return arr[idx];
}

/// @brief Write an element after checking bounds.
/// @param arr Array payload pointer.
/// @param idx Zero-based index to write.
/// @param value Value to store in the array.
void rt_arr_i32_set(int32_t *arr, size_t idx, int32_t value) {
    rt_arr_i32_validate_bounds(arr, idx);
    arr[idx] = value;
}

/// @brief Read an element after the compiler has proved the access in-bounds.
/// @details This out-of-line ABI surface lets native backends call the fast path
///          directly; it deliberately preserves the checked helper for all
///          unoptimized and unverifiable call sites.
/// @param arr Non-null array payload.
/// @param idx Compiler-proven in-bounds index.
/// @return Value stored at @p idx.
int32_t rt_arr_i32_get_fast(int32_t *arr, size_t idx) {
    return arr[idx];
}

/// @brief Write an element after the compiler has proved the access in-bounds.
/// @details Bounds checks must dominate calls to this helper. Keeping the helper
///          separate from the checked entry point prevents accidental unchecked
///          access in O0 code paths.
/// @param arr Non-null array payload.
/// @param idx Compiler-proven in-bounds index.
/// @param value Value to store.
void rt_arr_i32_set_fast(int32_t *arr, size_t idx, int32_t value) {
    arr[idx] = value;
}

/// @brief Copy @p count elements between array payloads.
/// @details Validates that both payloads are non-null when copying a non-empty
///          range and then performs a `memcpy`.  Bounds are assumed to have been
///          checked by the caller.
/// @param dst Destination array payload; must be non-null when @p count > 0.
/// @param src Source array payload; must be non-null when @p count > 0.
/// @param count Number of elements to copy.
void rt_arr_i32_copy_payload(int32_t *dst, const int32_t *src, size_t count) {
    if (count == 0)
        return;

    if (!dst || !src)
        rt_arr_oob_panic(0, count);

    if (count > SIZE_MAX / sizeof(int32_t))
        rt_arr_oob_panic(0, count);
    memcpy(dst, src, count * sizeof(int32_t));
}

/// @brief Reallocate unique i32 array storage to a requested length.
/// @param[in,out] hdr_inout Header pointer updated after reallocation.
/// @param[in,out] payload_inout Payload pointer updated after reallocation.
/// @param new_len Requested logical length.
/// @return Zero on success or `-1` on size/allocation/header failure.
/// @note Generated by the shared runtime-array helper macro.
RT_ARR_DEFINE_GROW_IN_PLACE_FN(rt_arr_i32_grow_in_place, int32_t, rt_arr_i32_payload_bytes)
/// @brief Resize an i32 runtime array under copy-on-write ownership rules.
/// @details Shared arrays are copied, while unique arrays may grow in place;
///          retained elements are preserved up to the smaller logical length.
/// @param[in,out] a_inout Address of the array payload handle; a null payload
///                allocates a fresh array.
/// @param new_len Requested logical length.
/// @return Zero on success or `-1` on invalid input or allocation failure.
/// @note Generated by the shared runtime-array helper macro.
RT_ARR_DEFINE_RESIZE_FN(rt_arr_i32_resize,
                        int32_t,
                        rt_arr_i32_hdr,
                        rt_arr_i32_assert_header,
                        rt_arr_i32_new,
                        rt_arr_i32_copy_payload,
                        rt_arr_i32_release,
                        rt_arr_i32_grow_in_place)
