//===----------------------------------------------------------------------===//
/// @file
/// @brief Implements reference-counted arrays of runtime string handles.
/// @details Each non-null slot owns one retained string reference. Reads create
///          a retained reference for the caller, writes retain-before-release
///          for self-assignment safety, and only the container's final release
///          drops slot references and frees backing storage. Header validation
///          supports recoverable runtime trap hooks.
///
//
// Part of the Zanna project, under the GNU GPL v3.
// See LICENSE for license information.
//
//===----------------------------------------------------------------------===//
//
// File: src/runtime/arrays/rt_array_str.c
// Purpose: Implements dynamic string array helpers backing BASIC string array
//          (DIM s$()) operations. Each element is a reference-counted rt_string
//          handle; the array manages retain/release for every element as they
//          are inserted, overwritten, or the array is freed.
//
// Key invariants:
//   - Each rt_string element is independently reference-counted.
//   - Writing to a slot releases the previous string and retains the new one.
//   - Array teardown releases all string references exactly once.
//   - The array itself is reference-counted through the heap allocator.
//   - Out-of-bounds accesses trigger rt_arr_oob_panic and abort.
//   - Empty/NULL string slots are treated as empty strings, not null pointers.
//
// Ownership/Lifetime:
//   - The array holds strong references to all stored strings.
//   - Callers that retrieve elements receive retained references and must
//     release them when finished.
//   - The array is freed through the heap refcount API, which triggers element
//     release in the finalizer.
//
// Links: src/runtime/arrays/rt_array_str.h (public API),
//        src/runtime/arrays/rt_array.h (int32 base module, oob_panic),
//        src/runtime/rt_string.h (rt_string retain/release)
//
//===----------------------------------------------------------------------===//

#include "rt_array_str.h"
#include "rt_array.h" // for rt_arr_oob_panic
#include "rt_internal.h"

#include <assert.h>
#include <stddef.h>
#include <stdlib.h>
#include <string.h>

#include "rt_trap.h"

/// @brief Return the heap header preceding a string-array payload.
/// @param payload Array payload; may be `NULL`.
/// @return Header pointer, or `NULL`.
/// @note Generated by the shared runtime-array helper macro.
RT_ARR_DEFINE_HDR_FN(rt_arr_str_hdr, rt_string)
/// @brief Validate that a heap header describes a string runtime array.
/// @param hdr Header to validate.
/// @note Generated by the shared runtime-array helper macro.
RT_ARR_DEFINE_ASSERT_HEADER_FN(rt_arr_str_assert_header, RT_ELEM_STR)

/// @brief Validate that a heap header describes a string array.
/// @details The generated assertion helper raises the existing diagnostic, but
///          has a void return. This wrapper exposes a boolean result so callers
///          can stop when a recoverable trap hook returns control.
/// @param hdr Heap header to validate.
/// @return Non-zero for a valid string-array header, zero after reporting a
///         header validation failure.
static int rt_arr_str_header_valid(rt_heap_hdr_t *hdr) {
    if (!hdr || hdr->kind != RT_HEAP_ARRAY || hdr->elem_kind != RT_ELEM_STR) {
        rt_trap("rt_array: corrupted header");
        return 0;
    }
    return 1;
}

/// @brief Allocate a new array of string handles.
/// @details Allocates an array with @p len slots for string pointers, all
///          initialized to NULL. The array itself is reference-counted via
///          the heap allocator.
/// @param len Requested element count.
/// @return Pointer to the array payload, or NULL when allocation fails.
rt_string *rt_arr_str_alloc(size_t len) {
    // Allocate array with RT_ELEM_STR element kind
    rt_string *arr =
        (rt_string *)rt_heap_alloc(RT_HEAP_ARRAY, RT_ELEM_STR, sizeof(rt_string), len, len);

    // rt_heap_alloc already zero-initializes memory, so all slots are NULL
    return arr;
}

/// @brief Release one array reference and finalize elements on the last release.
/// @details Decrements the container reference count without immediately freeing
///          its storage. Shared aliases leave every slot untouched. Only the
///          final owner releases the stored strings and reclaims the container.
/// @param arr Array payload pointer (may be NULL).
/// @param size Historical caller-supplied element count; ignored because the
///             heap header owns the authoritative length.
void rt_arr_str_release(rt_string *arr, size_t size) {
    if (!arr)
        return;

    rt_heap_hdr_t *hdr = rt_arr_str_hdr(arr);
    if (!rt_arr_str_header_valid(hdr))
        return;
    rt_arr_str_assert_header(hdr);

    (void)size;

    size_t refs = rt_heap_release_deferred(arr);
    if (refs != 0)
        return;

    // Release each string element using the heap header's authoritative length.
    for (size_t i = 0; i < hdr->len; ++i) {
        rt_str_release_maybe(arr[i]);
        arr[i] = NULL; // Clear slot after release
    }

    rt_heap_free_zero_ref(arr);
}

/// @brief Read string element at index @p idx and return a retained handle.
/// @details Returns the string at @p idx after incrementing its reference count.
///          The caller must release the returned handle when done.
/// @param arr Array payload pointer; must be non-null.
/// @param idx Zero-based index within the array length.
/// @return String handle at @p idx (retained for caller), or NULL if slot is empty.
rt_string rt_arr_str_get(rt_string *arr, size_t idx) {
    if (!arr)
        rt_trap("rt_arr_str_get: null array");
    if (!arr)
        return NULL;

    rt_heap_hdr_t *hdr = rt_arr_str_hdr(arr);
    if (!rt_arr_str_header_valid(hdr))
        return NULL;
    rt_arr_str_assert_header(hdr);

    if (idx >= hdr->len)
        rt_arr_oob_panic(idx, hdr->len);
    if (idx >= hdr->len)
        return NULL;

    rt_string value = arr[idx];

    // Retain before returning to caller (transfer semantics)
    rt_str_retain_maybe(value);

    return value;
}

/// @brief Write @p value to index @p idx with proper reference counting.
/// @details Retains the new value, releases the old value, then stores.
///          This maintains correct ownership semantics for the string handles.
/// @param arr Array payload pointer; must be non-null.
/// @param idx Zero-based index within the array length.
/// @param value String handle to store (may be NULL); will be retained.
void rt_arr_str_put(rt_string *arr, size_t idx, rt_string value) {
    if (!arr)
        rt_trap("rt_arr_str_put: null array");
    if (!arr)
        return;

    rt_heap_hdr_t *hdr = rt_arr_str_hdr(arr);
    if (!rt_arr_str_header_valid(hdr))
        return;
    rt_arr_str_assert_header(hdr);

    if (idx >= hdr->len)
        rt_arr_oob_panic(idx, hdr->len);
    if (idx >= hdr->len)
        return;

    // Retain new value first (in case value == arr[idx])
    rt_str_retain_maybe(value);

    // Release old value
    rt_str_release_maybe(arr[idx]);

    // Store new value
    arr[idx] = value;
}

/// @brief Query the current logical length of a string array.
/// @details Returns the element count stored in the heap header.
/// @param arr Array payload pointer.
/// @return Number of accessible elements; 0 when @p arr is NULL.
size_t rt_arr_str_len(rt_string *arr) {
    if (!arr)
        return 0;

    rt_heap_hdr_t *hdr = rt_arr_str_hdr(arr);
    if (!rt_arr_str_header_valid(hdr))
        return 0;
    rt_arr_str_assert_header(hdr);

    return hdr->len;
}
